services:
  pcp:
    image: quay.io/performancecopilot/pcp:latest
    privileged: true
    ports:
      - "44322:44322"
    environment:
      KEY_SERVERS: redis-stack:6379
    depends_on:
      - redis-stack

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
