apiVersion: 1
datasources:
  - name: PCP Valkey
    type: performancecopilot-valkey-datasource
    access: proxy
    url: http://pcp:44322
    isDefault: true
    editable: true

  - name: PCP Vector
    type: performancecopilot-vector-datasource
    access: proxy
    url: http://pcp:44322
    editable: true
